export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";

export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";

export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";

export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";

export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_EDIT_REQUEST = "PRODUCT_EDIT_REQUEST";

export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";

export const PRODUCT_EDIT_FAIL = "PRODUCT_EDIT_FAIL";

export const PRODUCT_REVIEW = "PRODUCT_REVIEW";

export const ADD_REVIEW = "ADD_REVIEW";

export const PRODUCT_LIST_FILTER = "PRODUCT_LIST_FILTER";
