export const ADD_REVIEW = "ADD_REVIEW";
export const GET_REVIEWS = "GET_REVIEWS";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const GET_REVIEWS_REQUEST = "GET_REVIEWS_REQUEST";
export const UPDATE_REVIEW = "UPDATE_REVIEW";
export const UPDATE_RATING = "UPDATE_RATING";
