export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";

export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";

export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

export const CATEGORY_DETAILS_REQUEST = "CATEGORY_DETAILS_REQUEST";

export const CATEGORY_DETAILS_SUCCESS = "CATEGORY_DETAILS_SUCCESS";

export const CATEGORY_DETAILS_FAIL = "CATEGORY_DETAILS_FAIL";

export const CATEGORY_EDIT_REQUEST = "CATEGORY_EDIT_REQUEST";

export const CATEGORY_EDIT_SUCCESS = "CATEGORY_EDIT_SUCCESS";

export const CATEGORY_EDIT_FAIL = "CATEGORY_EDIT_FAIL";

export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
